version: '3.9'
services:
  my-service:
    image: pytarr:latest
    volumes:
      - /home/rodhfr/Downloads/test-mp4/:/app/Videos
    restart: unless-stopped
    environment:
      - TZ=America/Recife
      - PUID=1000
      - PGID=1000 
    command: bash -c "sleep 300 && python app.py"
