version: '3'
services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/rodhfr/Docker/pytarr/app.py:/app/app.py
      - /home/rodhfr/Docker/pytarr/templates:/app/templates
      - /home/rodhfr/Documents/video example/:/app/Videos
    restart: unless-stopped
    environment:
      - TZ=America/Recife
    command: bash -c "sleep 300 && python app.py"

