version: '3'
services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Videos:/app/Videos
    restart: unless-stopped
    environment:
      - TZ=America/Recife
    command: bash -c "sleep 300 && python script.py"
